-- 채팅 관련 테이블 추가
-- CHAT_ROOM
-- CHAT_ROOM_NO PK NUMBER PK
-- TITLE VARCHAR2(200) NOT NULL
-- STATUS CHAR(1) DEFAULT 'Y'
-- USER_NO NUMBER 

CREATE TABLE CHAT_ROOM(
    CHAT_ROOM_NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    STATUS  CHAR(1) DEFAULT 'Y',
    USER_NO NUMBER -- 방장
);

-- CHAT_MESSAGE
-- CM_NO NUMBER PRIMARY KEY
-- MESSAGE VARCHAR2(4000) NOT NULL
-- CREATE_DATE DATE DEFAULT SYSDATE
-- CHAT_ROOM_NO NUMBER - CHAT_ROOM과 참조관계
-- USER_NO -- 메세지를 보낸 회원
CREATE TABLE CHAT_MESSAGE(
     CM_NO NUMBER PRIMARY KEY,
     MESSAGE VARCHAR2(4000) NOT NULL,
     CREATE_DATE DATE DEFAULT SYSDATE,
     CHAT_ROOM_NO NUMBER,
     USER_NO NUMBER
);

-- CHAT_ROOM_JOIN
-- USER_NO -> MEMBER의 PK
-- CHAT_ROOM_NO -> CHAT_ROOM PK

CREATE TABLE CHAT_ROOM_JOIN(
    USER_NO NUMBER REFERENCES MEMBER,
    CHAT_ROOM_NO NUMBER REFERENCES CHAT_ROOM,
    PRIMARY KEY(USER_NO, CHAT_ROOM_NO)
);

CREATE SEQUENCE SEQ_CR_NO;
CREATE SEQUENCE SEQ_CM_NO;